server:
   port: 8080
   error:
      include-message: always

spring:
   datasource:
      url: jdbc:mysql://smoothstack-project.cqxybfmjssty.us-east-2.rds.amazonaws.com:3306/utopia
      username: admin
      password: password
   jpa:
      hibernate:
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      
   
# For logging SQL statements   
#logging:
#   level:
#      org:
#         hibernate:
#            SQL: debug
#            type: trace